-- =============================================================================
-- Security: read-only analytical role for the AI Copilot (run as ACCOUNTADMIN)
-- =============================================================================

USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS ANALYTICS_AI_READONLY
  COMMENT = 'Read-only role for AI Business Analytics Copilot query execution';

CREATE ROLE IF NOT EXISTS ANALYTICS_AI_LOADER
  COMMENT = 'Loader role for Phase 1 RAW ingest (not used by the Streamlit app)';

-- Warehouse (XS is enough for MVP)
CREATE WAREHOUSE IF NOT EXISTS ANALYTICS_WH_XS
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Small warehouse for AI analytics MVP';

GRANT USAGE ON WAREHOUSE ANALYTICS_WH_XS TO ROLE ANALYTICS_AI_READONLY;
GRANT USAGE ON WAREHOUSE ANALYTICS_WH_XS TO ROLE ANALYTICS_AI_LOADER;

GRANT USAGE ON DATABASE ANALYTICS_AI_DB TO ROLE ANALYTICS_AI_READONLY;
GRANT USAGE ON DATABASE ANALYTICS_AI_DB TO ROLE ANALYTICS_AI_LOADER;

GRANT USAGE ON SCHEMA ANALYTICS_AI_DB.RAW TO ROLE ANALYTICS_AI_READONLY;
GRANT USAGE ON SCHEMA ANALYTICS_AI_DB.CURATED TO ROLE ANALYTICS_AI_READONLY;
GRANT USAGE ON SCHEMA ANALYTICS_AI_DB.ANALYTICS TO ROLE ANALYTICS_AI_READONLY;
GRANT USAGE ON SCHEMA ANALYTICS_AI_DB.AI TO ROLE ANALYTICS_AI_READONLY;

GRANT SELECT ON ALL TABLES IN SCHEMA ANALYTICS_AI_DB.RAW TO ROLE ANALYTICS_AI_READONLY;
GRANT SELECT ON ALL TABLES IN SCHEMA ANALYTICS_AI_DB.CURATED TO ROLE ANALYTICS_AI_READONLY;
GRANT SELECT ON ALL TABLES IN SCHEMA ANALYTICS_AI_DB.ANALYTICS TO ROLE ANALYTICS_AI_READONLY;
GRANT SELECT ON ALL TABLES IN SCHEMA ANALYTICS_AI_DB.AI TO ROLE ANALYTICS_AI_READONLY;

GRANT SELECT ON FUTURE TABLES IN SCHEMA ANALYTICS_AI_DB.RAW TO ROLE ANALYTICS_AI_READONLY;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ANALYTICS_AI_DB.CURATED TO ROLE ANALYTICS_AI_READONLY;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ANALYTICS_AI_DB.ANALYTICS TO ROLE ANALYTICS_AI_READONLY;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ANALYTICS_AI_DB.AI TO ROLE ANALYTICS_AI_READONLY;

-- Loader needs write on RAW only
GRANT USAGE ON SCHEMA ANALYTICS_AI_DB.RAW TO ROLE ANALYTICS_AI_LOADER;
GRANT ALL ON SCHEMA ANALYTICS_AI_DB.RAW TO ROLE ANALYTICS_AI_LOADER;
GRANT ALL ON ALL TABLES IN SCHEMA ANALYTICS_AI_DB.RAW TO ROLE ANALYTICS_AI_LOADER;
GRANT ALL ON FUTURE TABLES IN SCHEMA ANALYTICS_AI_DB.RAW TO ROLE ANALYTICS_AI_LOADER;

-- Assign to your user (edit username)
-- GRANT ROLE ANALYTICS_AI_READONLY TO USER YOUR_USER;
-- GRANT ROLE ANALYTICS_AI_LOADER TO USER YOUR_USER;
