-- =============================================================================
-- Phase 14: Grants for Streamlit-in-Snowflake (run as ACCOUNTADMIN)
-- =============================================================================

USE ROLE ACCOUNTADMIN;
USE DATABASE ANALYTICS_AI_DB;

-- Read-only analytical role (create if missing)
CREATE ROLE IF NOT EXISTS ANALYTICS_AI_READONLY
  COMMENT = 'Read-only role for AI Business Analytics Copilot';

GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE ANALYTICS_AI_READONLY;

GRANT USAGE ON DATABASE ANALYTICS_AI_DB TO ROLE ANALYTICS_AI_READONLY;

GRANT USAGE ON SCHEMA RAW TO ROLE ANALYTICS_AI_READONLY;
GRANT USAGE ON SCHEMA CURATED TO ROLE ANALYTICS_AI_READONLY;
GRANT USAGE ON SCHEMA ANALYTICS TO ROLE ANALYTICS_AI_READONLY;
GRANT USAGE ON SCHEMA AI TO ROLE ANALYTICS_AI_READONLY;

GRANT SELECT ON ALL TABLES IN SCHEMA RAW TO ROLE ANALYTICS_AI_READONLY;
GRANT SELECT ON ALL TABLES IN SCHEMA CURATED TO ROLE ANALYTICS_AI_READONLY;
GRANT SELECT ON ALL TABLES IN SCHEMA ANALYTICS TO ROLE ANALYTICS_AI_READONLY;
GRANT SELECT ON ALL TABLES IN SCHEMA AI TO ROLE ANALYTICS_AI_READONLY;
GRANT SELECT ON ALL VIEWS IN SCHEMA CURATED TO ROLE ANALYTICS_AI_READONLY;
GRANT SELECT ON ALL VIEWS IN SCHEMA ANALYTICS TO ROLE ANALYTICS_AI_READONLY;

GRANT SELECT ON FUTURE TABLES IN SCHEMA RAW TO ROLE ANALYTICS_AI_READONLY;
GRANT SELECT ON FUTURE TABLES IN SCHEMA CURATED TO ROLE ANALYTICS_AI_READONLY;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ANALYTICS TO ROLE ANALYTICS_AI_READONLY;
GRANT SELECT ON FUTURE TABLES IN SCHEMA AI TO ROLE ANALYTICS_AI_READONLY;

-- Allow the app to write observability rows
GRANT INSERT ON TABLE AI.QUERY_LOG TO ROLE ANALYTICS_AI_READONLY;

-- Optional Cortex access (account-dependent)
-- GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE ANALYTICS_AI_READONLY;

-- After the Streamlit object exists, grant usage (edit name if different):
-- GRANT USAGE ON STREAMLIT ANALYTICS_AI_DB.AI.AI_BUSINESS_ANALYTICS_COPILOT
--   TO ROLE ANALYTICS_AI_READONLY;

-- GRANT ROLE ANALYTICS_AI_READONLY TO USER SANAT2011;
